# PickPocket config file v0.2
PickPocketTool: 325
DamageOnFail: 1
LoseToolonFail: true
FailToSteal: [PickPocket] Your hand slipped.
ItemStolen: [PickPocket] Attempt successful.
TryToStealYou: [PickPocket] %n tried to pickpocket you!